import type { DemoReviewFile, DemoReviewSection } from './mockReviewTypes'

export const demoReviewFiles: DemoReviewFile[] = [
  {
    path: 'src/generated/example/File001.tsx',
    additions: 3,
    deletions: 1,
    status: 'approved',
    reviewers: ['reviewer-2', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 001',
  },
  {
    path: 'src/generated/example/File002.tsx',
    additions: 6,
    deletions: 2,
    status: 'changes_requested',
    reviewers: ['reviewer-3', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 002',
  },
  {
    path: 'src/generated/example/File003.tsx',
    additions: 9,
    deletions: 3,
    status: 'commented',
    reviewers: ['reviewer-4', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 003',
  },
  {
    path: 'src/generated/example/File004.tsx',
    additions: 12,
    deletions: 4,
    status: 'pending',
    reviewers: ['reviewer-5', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 004',
  },
  {
    path: 'src/generated/example/File005.tsx',
    additions: 15,
    deletions: 5,
    status: 'approved',
    reviewers: ['reviewer-1', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 005',
  },
  {
    path: 'src/generated/example/File006.tsx',
    additions: 18,
    deletions: 6,
    status: 'changes_requested',
    reviewers: ['reviewer-2', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 006',
  },
  {
    path: 'src/generated/example/File007.tsx',
    additions: 21,
    deletions: 7,
    status: 'commented',
    reviewers: ['reviewer-3', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 007',
  },
  {
    path: 'src/generated/example/File008.tsx',
    additions: 24,
    deletions: 8,
    status: 'pending',
    reviewers: ['reviewer-4', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 008',
  },
  {
    path: 'src/generated/example/File009.tsx',
    additions: 27,
    deletions: 9,
    status: 'approved',
    reviewers: ['reviewer-5', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 009',
  },
  {
    path: 'src/generated/example/File010.tsx',
    additions: 30,
    deletions: 10,
    status: 'changes_requested',
    reviewers: ['reviewer-1', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 010',
  },
  {
    path: 'src/generated/example/File011.tsx',
    additions: 33,
    deletions: 0,
    status: 'commented',
    reviewers: ['reviewer-2', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 011',
  },
  {
    path: 'src/generated/example/File012.tsx',
    additions: 36,
    deletions: 1,
    status: 'pending',
    reviewers: ['reviewer-3', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 012',
  },
  {
    path: 'src/generated/example/File013.tsx',
    additions: 39,
    deletions: 2,
    status: 'approved',
    reviewers: ['reviewer-4', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 013',
  },
  {
    path: 'src/generated/example/File014.tsx',
    additions: 42,
    deletions: 3,
    status: 'changes_requested',
    reviewers: ['reviewer-5', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 014',
  },
  {
    path: 'src/generated/example/File015.tsx',
    additions: 45,
    deletions: 4,
    status: 'commented',
    reviewers: ['reviewer-1', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 015',
  },
  {
    path: 'src/generated/example/File016.tsx',
    additions: 48,
    deletions: 5,
    status: 'pending',
    reviewers: ['reviewer-2', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 016',
  },
  {
    path: 'src/generated/example/File017.tsx',
    additions: 51,
    deletions: 6,
    status: 'approved',
    reviewers: ['reviewer-3', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 017',
  },
  {
    path: 'src/generated/example/File018.tsx',
    additions: 54,
    deletions: 7,
    status: 'changes_requested',
    reviewers: ['reviewer-4', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 018',
  },
  {
    path: 'src/generated/example/File019.tsx',
    additions: 57,
    deletions: 8,
    status: 'commented',
    reviewers: ['reviewer-5', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 019',
  },
  {
    path: 'src/generated/example/File020.tsx',
    additions: 60,
    deletions: 9,
    status: 'pending',
    reviewers: ['reviewer-1', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 020',
  },
  {
    path: 'src/generated/example/File021.tsx',
    additions: 63,
    deletions: 10,
    status: 'approved',
    reviewers: ['reviewer-2', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 021',
  },
  {
    path: 'src/generated/example/File022.tsx',
    additions: 66,
    deletions: 0,
    status: 'changes_requested',
    reviewers: ['reviewer-3', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 022',
  },
  {
    path: 'src/generated/example/File023.tsx',
    additions: 69,
    deletions: 1,
    status: 'commented',
    reviewers: ['reviewer-4', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 023',
  },
  {
    path: 'src/generated/example/File024.tsx',
    additions: 72,
    deletions: 2,
    status: 'pending',
    reviewers: ['reviewer-5', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 024',
  },
  {
    path: 'src/generated/example/File025.tsx',
    additions: 75,
    deletions: 3,
    status: 'approved',
    reviewers: ['reviewer-1', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 025',
  },
  {
    path: 'src/generated/example/File026.tsx',
    additions: 78,
    deletions: 4,
    status: 'changes_requested',
    reviewers: ['reviewer-2', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 026',
  },
  {
    path: 'src/generated/example/File027.tsx',
    additions: 81,
    deletions: 5,
    status: 'commented',
    reviewers: ['reviewer-3', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 027',
  },
  {
    path: 'src/generated/example/File028.tsx',
    additions: 84,
    deletions: 6,
    status: 'pending',
    reviewers: ['reviewer-4', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 028',
  },
  {
    path: 'src/generated/example/File029.tsx',
    additions: 87,
    deletions: 7,
    status: 'approved',
    reviewers: ['reviewer-5', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 029',
  },
  {
    path: 'src/generated/example/File030.tsx',
    additions: 90,
    deletions: 8,
    status: 'changes_requested',
    reviewers: ['reviewer-1', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 030',
  },
  {
    path: 'src/generated/example/File031.tsx',
    additions: 93,
    deletions: 9,
    status: 'commented',
    reviewers: ['reviewer-2', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 031',
  },
  {
    path: 'src/generated/example/File032.tsx',
    additions: 96,
    deletions: 10,
    status: 'pending',
    reviewers: ['reviewer-3', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 032',
  },
  {
    path: 'src/generated/example/File033.tsx',
    additions: 99,
    deletions: 0,
    status: 'approved',
    reviewers: ['reviewer-4', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 033',
  },
  {
    path: 'src/generated/example/File034.tsx',
    additions: 102,
    deletions: 1,
    status: 'changes_requested',
    reviewers: ['reviewer-5', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 034',
  },
  {
    path: 'src/generated/example/File035.tsx',
    additions: 105,
    deletions: 2,
    status: 'commented',
    reviewers: ['reviewer-1', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 035',
  },
  {
    path: 'src/generated/example/File036.tsx',
    additions: 108,
    deletions: 3,
    status: 'pending',
    reviewers: ['reviewer-2', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 036',
  },
  {
    path: 'src/generated/example/File037.tsx',
    additions: 111,
    deletions: 4,
    status: 'approved',
    reviewers: ['reviewer-3', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 037',
  },
  {
    path: 'src/generated/example/File038.tsx',
    additions: 114,
    deletions: 5,
    status: 'changes_requested',
    reviewers: ['reviewer-4', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 038',
  },
  {
    path: 'src/generated/example/File039.tsx',
    additions: 117,
    deletions: 6,
    status: 'commented',
    reviewers: ['reviewer-5', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 039',
  },
  {
    path: 'src/generated/example/File040.tsx',
    additions: 120,
    deletions: 7,
    status: 'pending',
    reviewers: ['reviewer-1', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 040',
  },
  {
    path: 'src/generated/example/File041.tsx',
    additions: 123,
    deletions: 8,
    status: 'approved',
    reviewers: ['reviewer-2', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 041',
  },
  {
    path: 'src/generated/example/File042.tsx',
    additions: 126,
    deletions: 9,
    status: 'changes_requested',
    reviewers: ['reviewer-3', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 042',
  },
  {
    path: 'src/generated/example/File043.tsx',
    additions: 129,
    deletions: 10,
    status: 'commented',
    reviewers: ['reviewer-4', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 043',
  },
  {
    path: 'src/generated/example/File044.tsx',
    additions: 132,
    deletions: 0,
    status: 'pending',
    reviewers: ['reviewer-5', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 044',
  },
  {
    path: 'src/generated/example/File045.tsx',
    additions: 135,
    deletions: 1,
    status: 'approved',
    reviewers: ['reviewer-1', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 045',
  },
  {
    path: 'src/generated/example/File046.tsx',
    additions: 138,
    deletions: 2,
    status: 'changes_requested',
    reviewers: ['reviewer-2', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 046',
  },
  {
    path: 'src/generated/example/File047.tsx',
    additions: 141,
    deletions: 3,
    status: 'commented',
    reviewers: ['reviewer-3', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 047',
  },
  {
    path: 'src/generated/example/File048.tsx',
    additions: 144,
    deletions: 4,
    status: 'pending',
    reviewers: ['reviewer-4', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 048',
  },
  {
    path: 'src/generated/example/File049.tsx',
    additions: 147,
    deletions: 5,
    status: 'approved',
    reviewers: ['reviewer-5', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 049',
  },
  {
    path: 'src/generated/example/File050.tsx',
    additions: 150,
    deletions: 6,
    status: 'changes_requested',
    reviewers: ['reviewer-1', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 050',
  },
  {
    path: 'src/generated/example/File051.tsx',
    additions: 153,
    deletions: 7,
    status: 'commented',
    reviewers: ['reviewer-2', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 051',
  },
  {
    path: 'src/generated/example/File052.tsx',
    additions: 156,
    deletions: 8,
    status: 'pending',
    reviewers: ['reviewer-3', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 052',
  },
  {
    path: 'src/generated/example/File053.tsx',
    additions: 159,
    deletions: 9,
    status: 'approved',
    reviewers: ['reviewer-4', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 053',
  },
  {
    path: 'src/generated/example/File054.tsx',
    additions: 162,
    deletions: 10,
    status: 'changes_requested',
    reviewers: ['reviewer-5', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 054',
  },
  {
    path: 'src/generated/example/File055.tsx',
    additions: 165,
    deletions: 0,
    status: 'commented',
    reviewers: ['reviewer-1', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 055',
  },
  {
    path: 'src/generated/example/File056.tsx',
    additions: 168,
    deletions: 1,
    status: 'pending',
    reviewers: ['reviewer-2', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 056',
  },
  {
    path: 'src/generated/example/File057.tsx',
    additions: 171,
    deletions: 2,
    status: 'approved',
    reviewers: ['reviewer-3', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 057',
  },
  {
    path: 'src/generated/example/File058.tsx',
    additions: 174,
    deletions: 3,
    status: 'changes_requested',
    reviewers: ['reviewer-4', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 058',
  },
  {
    path: 'src/generated/example/File059.tsx',
    additions: 177,
    deletions: 4,
    status: 'commented',
    reviewers: ['reviewer-5', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 059',
  },
  {
    path: 'src/generated/example/File060.tsx',
    additions: 180,
    deletions: 5,
    status: 'pending',
    reviewers: ['reviewer-1', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 060',
  },
  {
    path: 'src/generated/example/File061.tsx',
    additions: 183,
    deletions: 6,
    status: 'approved',
    reviewers: ['reviewer-2', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 061',
  },
  {
    path: 'src/generated/example/File062.tsx',
    additions: 186,
    deletions: 7,
    status: 'changes_requested',
    reviewers: ['reviewer-3', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 062',
  },
  {
    path: 'src/generated/example/File063.tsx',
    additions: 189,
    deletions: 8,
    status: 'commented',
    reviewers: ['reviewer-4', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 063',
  },
  {
    path: 'src/generated/example/File064.tsx',
    additions: 192,
    deletions: 9,
    status: 'pending',
    reviewers: ['reviewer-5', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 064',
  },
  {
    path: 'src/generated/example/File065.tsx',
    additions: 195,
    deletions: 10,
    status: 'approved',
    reviewers: ['reviewer-1', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 065',
  },
  {
    path: 'src/generated/example/File066.tsx',
    additions: 198,
    deletions: 0,
    status: 'changes_requested',
    reviewers: ['reviewer-2', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 066',
  },
  {
    path: 'src/generated/example/File067.tsx',
    additions: 201,
    deletions: 1,
    status: 'commented',
    reviewers: ['reviewer-3', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 067',
  },
  {
    path: 'src/generated/example/File068.tsx',
    additions: 204,
    deletions: 2,
    status: 'pending',
    reviewers: ['reviewer-4', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 068',
  },
  {
    path: 'src/generated/example/File069.tsx',
    additions: 207,
    deletions: 3,
    status: 'approved',
    reviewers: ['reviewer-5', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 069',
  },
  {
    path: 'src/generated/example/File070.tsx',
    additions: 210,
    deletions: 4,
    status: 'changes_requested',
    reviewers: ['reviewer-1', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 070',
  },
  {
    path: 'src/generated/example/File071.tsx',
    additions: 213,
    deletions: 5,
    status: 'commented',
    reviewers: ['reviewer-2', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 071',
  },
  {
    path: 'src/generated/example/File072.tsx',
    additions: 216,
    deletions: 6,
    status: 'pending',
    reviewers: ['reviewer-3', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 072',
  },
  {
    path: 'src/generated/example/File073.tsx',
    additions: 219,
    deletions: 7,
    status: 'approved',
    reviewers: ['reviewer-4', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 073',
  },
  {
    path: 'src/generated/example/File074.tsx',
    additions: 222,
    deletions: 8,
    status: 'changes_requested',
    reviewers: ['reviewer-5', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 074',
  },
  {
    path: 'src/generated/example/File075.tsx',
    additions: 225,
    deletions: 9,
    status: 'commented',
    reviewers: ['reviewer-1', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 075',
  },
  {
    path: 'src/generated/example/File076.tsx',
    additions: 228,
    deletions: 10,
    status: 'pending',
    reviewers: ['reviewer-2', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 076',
  },
  {
    path: 'src/generated/example/File077.tsx',
    additions: 231,
    deletions: 0,
    status: 'approved',
    reviewers: ['reviewer-3', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 077',
  },
  {
    path: 'src/generated/example/File078.tsx',
    additions: 234,
    deletions: 1,
    status: 'changes_requested',
    reviewers: ['reviewer-4', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 078',
  },
  {
    path: 'src/generated/example/File079.tsx',
    additions: 237,
    deletions: 2,
    status: 'commented',
    reviewers: ['reviewer-5', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 079',
  },
  {
    path: 'src/generated/example/File080.tsx',
    additions: 240,
    deletions: 3,
    status: 'pending',
    reviewers: ['reviewer-1', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 080',
  },
  {
    path: 'src/generated/example/File081.tsx',
    additions: 243,
    deletions: 4,
    status: 'approved',
    reviewers: ['reviewer-2', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 081',
  },
  {
    path: 'src/generated/example/File082.tsx',
    additions: 246,
    deletions: 5,
    status: 'changes_requested',
    reviewers: ['reviewer-3', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 082',
  },
  {
    path: 'src/generated/example/File083.tsx',
    additions: 249,
    deletions: 6,
    status: 'commented',
    reviewers: ['reviewer-4', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 083',
  },
  {
    path: 'src/generated/example/File084.tsx',
    additions: 252,
    deletions: 7,
    status: 'pending',
    reviewers: ['reviewer-5', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 084',
  },
  {
    path: 'src/generated/example/File085.tsx',
    additions: 255,
    deletions: 8,
    status: 'approved',
    reviewers: ['reviewer-1', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 085',
  },
  {
    path: 'src/generated/example/File086.tsx',
    additions: 258,
    deletions: 9,
    status: 'changes_requested',
    reviewers: ['reviewer-2', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 086',
  },
  {
    path: 'src/generated/example/File087.tsx',
    additions: 261,
    deletions: 10,
    status: 'commented',
    reviewers: ['reviewer-3', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 087',
  },
  {
    path: 'src/generated/example/File088.tsx',
    additions: 264,
    deletions: 0,
    status: 'pending',
    reviewers: ['reviewer-4', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 088',
  },
  {
    path: 'src/generated/example/File089.tsx',
    additions: 267,
    deletions: 1,
    status: 'approved',
    reviewers: ['reviewer-5', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 089',
  },
  {
    path: 'src/generated/example/File090.tsx',
    additions: 270,
    deletions: 2,
    status: 'changes_requested',
    reviewers: ['reviewer-1', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 090',
  },
  {
    path: 'src/generated/example/File091.tsx',
    additions: 273,
    deletions: 3,
    status: 'commented',
    reviewers: ['reviewer-2', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 091',
  },
  {
    path: 'src/generated/example/File092.tsx',
    additions: 276,
    deletions: 4,
    status: 'pending',
    reviewers: ['reviewer-3', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 092',
  },
  {
    path: 'src/generated/example/File093.tsx',
    additions: 279,
    deletions: 5,
    status: 'approved',
    reviewers: ['reviewer-4', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 093',
  },
  {
    path: 'src/generated/example/File094.tsx',
    additions: 282,
    deletions: 6,
    status: 'changes_requested',
    reviewers: ['reviewer-5', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 094',
  },
  {
    path: 'src/generated/example/File095.tsx',
    additions: 285,
    deletions: 7,
    status: 'commented',
    reviewers: ['reviewer-1', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 095',
  },
  {
    path: 'src/generated/example/File096.tsx',
    additions: 288,
    deletions: 8,
    status: 'pending',
    reviewers: ['reviewer-2', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 096',
  },
  {
    path: 'src/generated/example/File097.tsx',
    additions: 291,
    deletions: 9,
    status: 'approved',
    reviewers: ['reviewer-3', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 097',
  },
  {
    path: 'src/generated/example/File098.tsx',
    additions: 294,
    deletions: 10,
    status: 'changes_requested',
    reviewers: ['reviewer-4', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 098',
  },
  {
    path: 'src/generated/example/File099.tsx',
    additions: 297,
    deletions: 0,
    status: 'commented',
    reviewers: ['reviewer-5', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 099',
  },
  {
    path: 'src/generated/example/File100.tsx',
    additions: 300,
    deletions: 1,
    status: 'pending',
    reviewers: ['reviewer-1', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 100',
  },
  {
    path: 'src/generated/example/File101.tsx',
    additions: 303,
    deletions: 2,
    status: 'approved',
    reviewers: ['reviewer-2', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 101',
  },
  {
    path: 'src/generated/example/File102.tsx',
    additions: 306,
    deletions: 3,
    status: 'changes_requested',
    reviewers: ['reviewer-3', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 102',
  },
  {
    path: 'src/generated/example/File103.tsx',
    additions: 309,
    deletions: 4,
    status: 'commented',
    reviewers: ['reviewer-4', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 103',
  },
  {
    path: 'src/generated/example/File104.tsx',
    additions: 312,
    deletions: 5,
    status: 'pending',
    reviewers: ['reviewer-5', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 104',
  },
  {
    path: 'src/generated/example/File105.tsx',
    additions: 315,
    deletions: 6,
    status: 'approved',
    reviewers: ['reviewer-1', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 105',
  },
  {
    path: 'src/generated/example/File106.tsx',
    additions: 318,
    deletions: 7,
    status: 'changes_requested',
    reviewers: ['reviewer-2', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 106',
  },
  {
    path: 'src/generated/example/File107.tsx',
    additions: 321,
    deletions: 8,
    status: 'commented',
    reviewers: ['reviewer-3', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 107',
  },
  {
    path: 'src/generated/example/File108.tsx',
    additions: 324,
    deletions: 9,
    status: 'pending',
    reviewers: ['reviewer-4', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 108',
  },
  {
    path: 'src/generated/example/File109.tsx',
    additions: 327,
    deletions: 10,
    status: 'approved',
    reviewers: ['reviewer-5', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 109',
  },
  {
    path: 'src/generated/example/File110.tsx',
    additions: 330,
    deletions: 0,
    status: 'changes_requested',
    reviewers: ['reviewer-1', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 110',
  },
  {
    path: 'src/generated/example/File111.tsx',
    additions: 333,
    deletions: 1,
    status: 'commented',
    reviewers: ['reviewer-2', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 111',
  },
  {
    path: 'src/generated/example/File112.tsx',
    additions: 336,
    deletions: 2,
    status: 'pending',
    reviewers: ['reviewer-3', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 112',
  },
  {
    path: 'src/generated/example/File113.tsx',
    additions: 339,
    deletions: 3,
    status: 'approved',
    reviewers: ['reviewer-4', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 113',
  },
  {
    path: 'src/generated/example/File114.tsx',
    additions: 342,
    deletions: 4,
    status: 'changes_requested',
    reviewers: ['reviewer-5', 'reviewer-3'],
    summary: 'Placeholder review summary for AB-2 screenshot row 114',
  },
  {
    path: 'src/generated/example/File115.tsx',
    additions: 345,
    deletions: 5,
    status: 'commented',
    reviewers: ['reviewer-1', 'reviewer-4'],
    summary: 'Placeholder review summary for AB-2 screenshot row 115',
  },
  {
    path: 'src/generated/example/File116.tsx',
    additions: 348,
    deletions: 6,
    status: 'pending',
    reviewers: ['reviewer-2', 'reviewer-5'],
    summary: 'Placeholder review summary for AB-2 screenshot row 116',
  },
  {
    path: 'src/generated/example/File117.tsx',
    additions: 351,
    deletions: 7,
    status: 'approved',
    reviewers: ['reviewer-3', 'reviewer-6'],
    summary: 'Placeholder review summary for AB-2 screenshot row 117',
  },
  {
    path: 'src/generated/example/File118.tsx',
    additions: 354,
    deletions: 8,
    status: 'changes_requested',
    reviewers: ['reviewer-4', 'reviewer-7'],
    summary: 'Placeholder review summary for AB-2 screenshot row 118',
  },
  {
    path: 'src/generated/example/File119.tsx',
    additions: 357,
    deletions: 9,
    status: 'commented',
    reviewers: ['reviewer-5', 'reviewer-1'],
    summary: 'Placeholder review summary for AB-2 screenshot row 119',
  },
  {
    path: 'src/generated/example/File120.tsx',
    additions: 360,
    deletions: 10,
    status: 'pending',
    reviewers: ['reviewer-1', 'reviewer-2'],
    summary: 'Placeholder review summary for AB-2 screenshot row 120',
  },
]

export const demoReviewSections: DemoReviewSection[] = [
  {
    title: 'Demo Review Section 01',
    description: 'Generated section 01 for AB-2 screenshot examples.',
    files: demoReviewFiles.slice(0, 12),
  },
  {
    title: 'Demo Review Section 02',
    description: 'Generated section 02 for AB-2 screenshot examples.',
    files: demoReviewFiles.slice(12, 24),
  },
  {
    title: 'Demo Review Section 03',
    description: 'Generated section 03 for AB-2 screenshot examples.',
    files: demoReviewFiles.slice(24, 36),
  },
  {
    title: 'Demo Review Section 04',
    description: 'Generated section 04 for AB-2 screenshot examples.',
    files: demoReviewFiles.slice(36, 48),
  },
  {
    title: 'Demo Review Section 05',
    description: 'Generated section 05 for AB-2 screenshot examples.',
    files: demoReviewFiles.slice(48, 60),
  },
  {
    title: 'Demo Review Section 06',
    description: 'Generated section 06 for AB-2 screenshot examples.',
    files: demoReviewFiles.slice(60, 72),
  },
  {
    title: 'Demo Review Section 07',
    description: 'Generated section 07 for AB-2 screenshot examples.',
    files: demoReviewFiles.slice(72, 84),
  },
  {
    title: 'Demo Review Section 08',
    description: 'Generated section 08 for AB-2 screenshot examples.',
    files: demoReviewFiles.slice(84, 96),
  },
  {
    title: 'Demo Review Section 09',
    description: 'Generated section 09 for AB-2 screenshot examples.',
    files: demoReviewFiles.slice(96, 108),
  },
  {
    title: 'Demo Review Section 10',
    description: 'Generated section 10 for AB-2 screenshot examples.',
    files: demoReviewFiles.slice(108, 120),
  },
]

export function summarizeDemoReviewFiles(files: DemoReviewFile[]) {
  return files.reduce(
    (summary, file) => ({
      additions: summary.additions + file.additions,
      deletions: summary.deletions + file.deletions,
      files: summary.files + 1,
    }),
    { additions: 0, deletions: 0, files: 0 },
  )
}
